# Use a Python base image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Install any needed dependencies specified in requirements.txt
RUN pip install --no-cache-dir flask requests

# Expose port 5003 to the outside world
EXPOSE 5003

# Define environment variable
ENV FLASK_APP=saga_orchestrator.py

# Run saga_orchestrator.py when the container launches
CMD ["flask", "run", "--host=0.0.0.0", "--port=5003"]
