apiVersion: apps/v1
kind: Deployment
metadata:
  name: saga-orchestrator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saga-orchestrator
  template:
    metadata:
      labels:
        app: saga-orchestrator
    spec:
      containers:
      - name: saga-orchestrator
        image: saga-orchestrator:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5003
---
apiVersion: v1
kind: Service
metadata:
  name: saga-orchestrator-service
spec:
  selector:
    app: saga-orchestrator
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5003
